### ISSUE TITLE
Icons in Vertico?

### ISSUE THREAD

**Issue by JosephFerano** [jdtsmith/kind-icon#23] opened 2022-08-23 10:06 UTC
Hi, thank you for the great package!

I'm using Vertico as the completion system as explained [here](https://github.com/minad/vertico#completion-at-point-and-completion-in-region) along with `consult-completion-in-region`.

I've tried a few things suggested in the readme, including calling this

```lisp
(setq completion-in-region-function #'consult-completion-in-region)
(setq completion-in-region-function (kind-icon-enhance-completion completion-in-region-function))
```
But I do not see any icons in vertico.

Is this possible and I'm doing something wrong or is this currently not possible at the moment? If I understand correctly, it would be a matter of unifying what [all-the-icons-completion](https://github.com/iyefrat/all-the-icons-completion) does with what *kind-icon* provides in terms of translating LSP info into icons?

**Comment by jdtsmith** [comment] 2022-08-23 16:46
I haven't tried it in vertico, but am open to any tweaks needed to make it work.  Perhaps you could start by trying to directly wrap the completion-in-region :

```elisp
(setq completion-in-region-function
      (kind-icon-enhance-completion
       (lambda (&rest args)
        (apply (if vertico-mode
                   #'consult-completion-in-region
                 #'completion--in-region)
               args))))
```

**Comment by JosephFerano** [comment] 2022-08-24 04:59
Thank you for the reply. ~~Unfortunately that code did not change anything~~. Let me know if there's anything I can help with. I'm learning elisp right now.

Edit: Some icons are showing up in elisp, but only the variables seem to be showing up;

![image](https://user-images.githubusercontent.com/2642263/186345760-48e3deb8-5730-44ee-b3d8-0e94830b50b0.png)

However, this seems to be the only one working. I tried C mode as well, nada.

**Comment by jdtsmith** [comment] 2022-08-31 17:44
That's good news; it looks like I'd expect.  emacs-lisp is completing only variables in that position (setq). Can you show an example of it not working as you were expecting?

**Comment by JosephFerano** [comment] 2022-09-08 05:42
Sure, here are some examples in C and elisp;

![Screenshot from 2022-09-08 12-29-10](https://user-images.githubusercontent.com/2642263/189043264-e7842a6e-4439-44db-bcdc-8bad0081ae25.png)
![Screenshot from 2022-09-08 12-30-50](https://user-images.githubusercontent.com/2642263/189043268-2720542d-7ec5-4ce1-b14e-f6701d8c644b.png)
![Screenshot from 2022-09-08 12-37-25](https://user-images.githubusercontent.com/2642263/189043273-6b79b22d-8bad-4aa9-97aa-522b5bc44d57.png)

So only elisp variables seem to be working, like you mentioned, with `setq`

**Comment by jdtsmith** [comment] 2022-09-08 14:07
Do these same completions work with corfu in buffer?  Can you disable the 0,1,2 numbering and check that as well?

**Comment by JosephFerano** [comment] 2022-09-10 03:06
I disabled `vertico-indexing` and enabled corfu. Everything works just fine in corfu, as expected, both in C and elisp. However, same results in vertico; only elisp variables are showing up.

**Comment by jdtsmith** [comment] 2022-09-10 21:51
I just tried this exact config and can't reproduce your issue:

![image](https://user-images.githubusercontent.com/93749/189502863-45aaeda3-2ab4-4585-bc09-813cf03e9e32.png)

I do notice that the default sorting is different between corfu and consult.  Do you have dabbrev or other CAPFs configured?   They don't offer any `:company-kind` info so naturally get no icons; perhaps those are being sorted to the front in consult but not corfu.   

I can look into this idea if you give me a precise reproduction recipe from `emacs -Q`.

**Comment by JosephFerano** [comment] 2022-09-12 08:33
I was able to reproduce with my config; apparently it's `marginalia` that's messing up `kind-icon` and I'm getting the behavior I'm describing. As soon as I disable `marginalia-mode`, I can see all of the `kind-icon`s in vertico. I'll need to investigate further but if you have any suggestions on how to fix this, I would appreciate it.

**Comment by JosephFerano** [comment] 2022-09-12 08:46
Let me include the reproduction steps; it's pretty much `emacs -Q` just with the straight.el bootstrapping at the beginning.

```lisp
;; straight.el bootstrap...

(straight-use-package 'vertico)
(straight-use-package 'consult)
(straight-use-package 'kind-icon)
(straight-use-package 'marginalia)
(vertico-mode t)
(setq completion-in-region-function #'consult-completion-in-region)
(setq completion-in-region-function (kind-icon-enhance-completion completion-in-region-function))

(marginalia-mode t)
```

Then do `C-M-i` for an elisp function and for a variable following `setq`. Also  in a C program none of the icons show up. Then turn off `marginalia-mode` and the icons show up.

**Comment by jdtsmith** [comment] 2022-09-12 13:21
OK that clarifies things.  marginalia has "automatic classifiers" which attempt to "guess" the completion category if none is set, and if it guesses some category, is then quite aggressive about overriding annotation/affixation functions.  In the case of a partial function call completion, it's guessing a category of `symbol`, and overriding the affixation function that kind-icon has setup (to show the docsig info).

The reason it works for me is I'm using a cape-super-ified completion-at-point-function, which has a default category `cape-super` already set.  So marginalia leaves that alone.  

I regard the aggressive overwriting of pre-set affixation functions as something of a marginalia bug, but I'm not sure @minad would agree.  The best scenario IMO would be for marginalia to notice a pre-existing affixation function, and _composite_ its information on top of that, rather than just replace it outright. 

You might open an issue about the matter at marginalia and link it here. 

In the meantime, you can force marginalia to _quit guessing categories_ like:

```elisp
  (setq completion-in-region-function
	(kind-icon-enhance-completion
	 (lambda (&rest args)
	   (let ((marginalia-classifiers nil))
	     (apply #'consult-completion-in-region args)))))
```

**Comment by minad** [comment] 2022-09-12 13:49
@jdtsmith

> I regard the aggressive overwriting of pre-set affixation functions as something of a marginalia bug, but I'm not sure @minad would agree. The best scenario IMO would be for marginalia to notice a pre-existing affixation function, and composite its information on top of that, rather than just replace it outright.

You know that I disagree, we discussed this. Why do you bring up this point again? Affixations are purely auxillary information, it doesn't hurt replacing it outright with *better* annotations. You also know that formatting affixations is a big PITA, so how do you imagine composing these functions?

If you don't like the annotations offered by Marginalia, you can replace them or disable them on a case by case basis. You can also disable the Marginalia classifiers or replace them with your own better classifiers. If the existing classifiers yield wrong results I am happy to accept improvement proposals, but the overall mechanism will stay as is.

**Comment by jdtsmith** [comment] 2022-09-12 13:55
I bring this point up again because I've had some additional thoughts about it.  I certainly understand the complexities of letting too many chefs prepare the meal.  I was imagining something simple like: if an affixation function already exists among the metadata, call it in addition to the marginalia affixation function.  If one sets the prefix and one sets the suffix, composite them (prefix from one, suffix from the other).  Otherwise, replace.

**Comment by minad** [comment] 2022-09-12 14:06
> I was imagining something simple like: if an affixation function already exists among the metadata, call it in addition to the marginalia affixation function. If one sets the prefix and one sets the suffix, composite them (prefix from one, suffix from the other). Otherwise, replace.

That's not a great idea. As you already mentioned it complicates the existing design. It can also have negative performance implications, since we have to call the other unpredicatable affixation function. I prefer to keep the current design. 

You just have to make sure that the packages are enabled in the right order. Marginalia first, then the icon package. As far as I know @iyefrat's all-the-icons-completion package coexists harmonically with Marginalia in that way, if some care is taken.

We could think about introducing some Marginalia hook to format the affixation prefix, but then you would have to write some Marginalia specific integration code - like for the Corfu margin formatter. Would this be preferable? Probably not, since the prefix formatter would then only apply if a Marginalia annotator is present, complicating things even more.

Anyway, the affixation/annotation business is a mess. I would prefer so much to have a better decoration-function, but this has also been discussed numerous times...

**Comment by jdtsmith** [comment] 2022-09-12 14:14
> You just have to make sure that the packages are enabled in the right order. Marginalia first, then the icon package. 

Interesting that they were able to work around this. About the only way I could imagine that working is for the icon package _also_ to wrap `completion-metadata-get` with some advice.  

I'll close this as fixed by the workaround above. @JosephFerano let me know if it doesn't work for any reason.

**Comment by minad** [comment] 2022-09-12 14:14
@iyefrat's package implements the composition you imagined. See https://github.com/iyefrat/all-the-icons-completion/blob/286e2c064a1298be0d8d4100dc91d7a7a554d04a/all-the-icons-completion.el#L81-L126. It is just a matter of where we implement the composition. Should it be part of Marginalia or part of the icon package? I don't have really good technical arguments here:

1. Marginalia is older and more widespread than icons (also the categories are important for Embark), so auxiliary icon packages should adapt.
2. Marginalia shouldn't call other affixation functions (unpredictable performance), while for the icon packages this doesn't matter, since you always have to pay the cost for the annotator anyway.
3. It is not nice to duplicate the affixation composition code across many packages. This would speak in favor of adding the relevant code to Marginalia.

**Closed as completed by jdtsmith** 2022-09-12 14:14 UTC

**Comment by jdtsmith** [comment] 2022-09-12 14:40
Funny I was just looking at that.  I do think around advice wrapping before-until advice also seems a bit fragile and is obviously order dependent.  When category is set or correctly guessed, the additional metadata marginalia provides for in-buffer-but-really-in-minibuffer completion is quite valuable, and you could see why people might prefer that heavier but more information-dense style, even at the cost of speed. 

I don't have a good solution.  Even a mythical hint-based alignment _decoration function_ wouldn't necessarily solve the particular issue of: when separate perhaps unrelated packages each would like to inject some decoration, who gets precedence?  An advice-wrapping  arms race seems less than ideal.  Such a last-minute metadata formatter might be an obvious place to do simple composition of the sort all-the-icons finagles.

**Comment by minad** [comment] 2022-09-12 14:49
> When category is set or correctly guessed...

Ideally, this should always be the case. I am happy to improve on this if there are good proposals on making the classification more robust. The good thing about the category is that we don't have to compose anything. There is just one category.

> ...even at the cost of speed.

Note that Marginalia annotators are usually quite efficient. We've put quite some work into that. On top we also cache the results during a completion session which helps with scrolling. The point I was making above is that I don't want to compose the Marginalia annotator with another unpredictable affixation function, which may be potentially slow such that we end up with twice the cost.

> Even a mythical hint-based alignment decoration function wouldn't necessarily solve the particular issue of...

For a decoration function the formatting would take place in the UI. Composing the plists of all the various decorations seems more plausible to me. Also composability could be kept in mind when designing the API. In contrast, the affixation-function is just a mess. It wasn't designed. It is the result of exposing an implementation detail of the default completion UI.

**Comment by JosephFerano** [comment] 2022-09-13 03:11
I appreciate y'all having the discussion, even if it's a little over my head.

@jdtsmith The snippet you provided for `completion-in-region-function` works, however, while this isn't necessarily an issue with `kind-icon` it doesn't play well with `all-the-icons-completion`. Everything seems to work well in elisp, but when I switch to C or Go source code, the icons disappear. If I disable `all-the-icons-completion`, the icons show up just fine in these aforementioned modes.

I can open up an issue over at the `all-the-icons-completion` repo and reference this issue. I don't quite follow what's going on so I'm assuming this is going to require a little bit of finessing between the two packages. Let me know if I can assist in anyway. I'm also on both the System Crafters and Doom discords, but I can also hop on IRC, at which point I'd be glad to go through any code so long as you're patient enough with me.

**Comment by jdtsmith** [comment] 2022-09-13 14:25
Hmmm...  I'd guess this is due to the way `all-the-icons-completion` wraps `completion-metadata-get` with advice. So now in your setup, _three sources_ are fighting to control the affixation-function and its prefix icon:

1. `kind-icon`: does not wrap, just adds a prefix-supplying affixation function (but only if no such function is already set) to `completion-extra-properties` at the lowest layer in the completion-in-region-function itself.
2. `marginalia`: wraps `completion-metadata-get` and overrides the affixation function, only if a completion "category" is set or guessed.
3. `all-the-icons-completion`: (if loaded _after_ marginalia) re-wraps `completion-metadata-get`, calls the affixation function and _prepends_ its icon to the prefix (close to what I was proposing marginalia do, above).

Pretty convoluted, and unfortunately the order with which you load the packages will matter.  But as you can see, `kind-icon` is the most meek, so is the most likely to get overridden, which seems to be happening for you.  If you disable marginalia in your C/Go buffers, does it work again?  Do you load all-the-icons-completion up last?  If you open an issue, see if there's a variable that could be bound to disable all-the-icons; I couldn't see anything obvious from a brief glance. 

(General note on the situation) — All of this would indeed be simpler if a "decoration-function" capability were implemented in Emacs.  Various tools could then "request" the inclusion of a flexible set of text decoration: prefix, suffix, column-or-right-aligned information, etc.  It would then be up to the decorator UI to composite all of this information together, and make the alignment look good.  Sort of like how CSS is used to style layers of HTML data.  But of course it would have to be backwards-compatible with the annotation/affixation stuff that is already out in the wild.  No small job.

**Comment by minad** [comment] 2022-09-13 14:37
To be fair it is kind of unusual to use both kind-icon and all-the-icons-completion together since these packages lead to different looks. Instead both kind-icon and all-the-icons-completion should provide icon sets for both minibuffer and in-buffer completion and use the same Marginalia-compatible mechanism to hook into the completion.
